# Generated by Django 2.1.2 on 2018-12-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(max_length=200),
        ),
    ]
