# Generated by Django 2.1.2 on 2018-12-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20181204_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
