# Generated by Django 2.1.2 on 2018-12-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_bedrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='dummy',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
