# Generated by Django 2.1.2 on 2018-12-04 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_dummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='dummy',
        ),
    ]
